[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "echo '=== Railway Root Directory Workaround ==='",
    "echo 'Checking if we need to navigate to frontend directory'",
    "pwd",
    "ls -la",
    "if [ -d 'frontend' ]; then echo 'Found frontend dir, copying files'; cp -r frontend/* .; fi",
    "echo '=== After potential copy ==='",
    "ls -la src/ || echo 'No src directory'",
    "ls -la src/lib/ || echo 'No src/lib directory'",
    "npm run build"
]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"