[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm ci --verbose"
]

[phases.build]
cmds = [
    "ls -la src/lib/",
    "ls -la src/pages/",
    "npm run build"
]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"