version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: lineup_db
    environment:
      POSTGRES_DB: lineup_db
      POSTGRES_USER: lineup_user
      POSTGRES_PASSWORD: lineup_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lineup_network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: lineup_backend
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://lineup_user:lineup_password@db:5432/lineup_db
      - ENVIRONMENT=development
      - DEBUG=True
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - db
    networks:
      - lineup_network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: lineup_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - lineup_network
    restart: unless-stopped
    command: npm run dev

volumes:
  postgres_data:

networks:
  lineup_network:
    driver: bridge
