[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "postgresql", "gcc", "pkg-config", "curl"]

[phases.install]
cmds = [
    "cd /app/backend && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Backend build phase completed'"
]

[start]
cmd = "cd /app/backend && echo 'Starting FastAPI...' && ls -la && /app/backend/venv/bin/python -c 'import app.main; print(\"App imported successfully\")' && /app/backend/venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --log-level debug"