[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "postgresql", "gcc", "pkg-config", "curl"]

[phases.install]
cmds = [
    "cd /app/backend && pip install --user -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Backend build phase completed'"
]

[start]
cmd = "cd /app/backend && echo 'Starting FastAPI...' && export PATH=$HOME/.local/bin:$PATH && which python3 && which uvicorn && python3 -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --log-level debug"