[phases.setup]
nixPkgs = ["python313", "postgresql", "gcc", "pkg-config", "curl"]

[phases.install]
cmds = [
    "cd backend",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Backend build phase completed'"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"