[build]
builder = "nixpacks"

[deploy]
startCommand = "cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT"

[environments.production]
variables = { 
  NODE_ENV = "production",
  VITE_API_BASE_URL = "https://line-up-backend-production.up.railway.app/api/v1",
  FORCE_HTTPS = "true"
}