"""add_unique_constraint_to_lineup_game_id

Revision ID: 15c430400671
Revises: a9125547b33a
Create Date: 2025-09-05 13:32:11.126705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c430400671'
down_revision: Union[str, Sequence[str], None] = 'a9125547b33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lineup_game_id', 'lineups', ['game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lineup_game_id', 'lineups', type_='unique')
    # ### end Alembic commands ###
