"""update_batting_order_range_for_pitcher

Revision ID: 7154d7a5f75d
Revises: ff74c77f9a57
Create Date: 2025-09-03 12:32:15.060267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7154d7a5f75d'
down_revision: Union[str, Sequence[str], None] = 'ff74c77f9a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
