"""add_is_professional_field_to_player

Revision ID: 7f975b3c5267
Revises: 7154d7a5f75d
Create Date: 2025-09-03 13:50:17.801937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f975b3c5267'
down_revision: Union[str, Sequence[str], None] = '7154d7a5f75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_professional', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_professional')
    # ### end Alembic commands ###
