"""remove_position_unique_constraint_for_p_duplicate

Revision ID: a66b3485a93b
Revises: 7203f5f530c9
Create Date: 2025-09-05 13:47:43.569878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66b3485a93b'
down_revision: Union[str, Sequence[str], None] = '7203f5f530c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_lineup_position'), 'lineup_players', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_lineup_position'), 'lineup_players', ['lineup_id', 'position'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
