"""add_team_our_team_and_player_team_id

Revision ID: b345b919726c
Revises: fb45a3da4c34
Create Date: 2025-09-05 10:14:08.845631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b345b919726c'
down_revision: Union[str, Sequence[str], None] = 'fb45a3da4c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lineup_players', 'position',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('uq_lineup_position_unique'), table_name='lineup_players', postgresql_where='(("position" IS NOT NULL) AND (("position")::text <> \'P\'::text))')
    op.create_unique_constraint('uq_lineup_position', 'lineup_players', ['lineup_id', 'position'])
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    op.add_column('teams', sa.Column('is_our_team', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_our_team')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'team_id')
    op.drop_constraint('uq_lineup_position', 'lineup_players', type_='unique')
    op.create_index(op.f('uq_lineup_position_unique'), 'lineup_players', ['lineup_id', 'position'], unique=True, postgresql_where='(("position" IS NOT NULL) AND (("position")::text <> \'P\'::text))')
    op.alter_column('lineup_players', 'position',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
