"""add_player_role_field

Revision ID: ff74c77f9a57
Revises: 6e773f63da2b
Create Date: 2025-09-03 12:10:54.761578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff74c77f9a57'
down_revision: Union[str, Sequence[str], None] = '6e773f63da2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 먼저 nullable=True로 컬럼 추가
    op.add_column('players', sa.Column('role', sa.Enum('PLAYER', 'MANAGER', 'COACH', 'MANAGER_OFFICE', 'PRESIDENT', 'ADVISOR', name='playerrole'), nullable=True))
    
    # 기존 데이터에 기본값 설정
    op.execute("UPDATE players SET role = 'PLAYER' WHERE role IS NULL")
    
    # 컬럼을 nullable=False로 변경
    op.alter_column('players', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'role')
    # ### end Alembic commands ###
